x-common-env: &common-env
  DEBUG: 'True'
  DB_ENGINE: postgresql
  DB_NAME: ${POSTGRES_DB:-scholaria}
  DB_USER: ${POSTGRES_USER:-postgres}
  DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  DB_HOST: postgres
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/0
  QDRANT_HOST: qdrant
  QDRANT_PORT: 6333
  QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME:-scholaria_documents}
  OPENAI_API_KEY: ${OPENAI_API_KEY:-changeme}
  OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL:-text-embedding-3-large}
  OPENAI_CHAT_MODEL: ${OPENAI_CHAT_MODEL:-gpt-4o-mini}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-jwt-secret}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    ports:
      - "${FASTAPI_PORT:-8001}:8001"
    environment:
      <<: *common-env
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
      FASTAPI_ALLOWED_ORIGINS: ${FASTAPI_ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000}
    volumes:
      - .:/app
      - uploads:/app/uploads
      - media:/app/media
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      jaeger:
        condition: service_started

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-scholaria}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  frontend:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8001/api/admin
      - VITE_BASE_PATH=/admin/
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    command: celery -A backend.celery_app worker --loglevel=info
    environment:
      <<: *common-env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - qdrant

  flower:
    image: mher/flower:2.0
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-flower}
    depends_on:
      - redis
      - celery-worker

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=info

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - jaeger

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  uploads:
  media:
  frontend_node_modules:
  prometheus_data:
  grafana_data:
