# Generated by Django 5.2.6 on 2025-09-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_context_contextitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='contexts',
            field=models.ManyToManyField(blank=True, related_name='topics', to='rag.context'),
        ),
    ]
