# Generated by Django 5.2.6 on 2025-09-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_topic_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='contextitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
