# Generated by Django 5.2.6 on 2025-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_add_uploaded_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of chunks created from this context'),
        ),
        migrations.AddField(
            model_name='context',
            name='original_content',
            field=models.TextField(blank=True, help_text='Full document content before chunking', null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current processing status of the context', max_length=20),
        ),
    ]
