# Generated by Django 5.2.6 on 2025-09-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_context_chunk_count_context_original_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question asked by the user')),
                ('answer', models.TextField(help_text='The answer provided by the system')),
                ('session_id', models.CharField(help_text='Session identifier to group related questions', max_length=255)),
                ('is_favorited', models.BooleanField(default=False, help_text='Whether this question is marked as favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_histories', to='rag.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
